# Generated by Django 2.2.6 on 2019-10-13 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('url_foto', models.CharField(max_length=255)),
                ('perfil_prof', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('url_imag', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo_archivo', models.CharField(max_length=10)),
                ('is_private', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolioapp.User')),
            ],
        ),
    ]
